# Why Numpy?

Numpy allow us create better data types for numerical manipulation, which are more efficient than regular Python data types.


In [1]:
#importing numpy
import numpy as np #very common practice
from IPython import display #this library will allow us to display data with type

# Creating arrays

In [23]:
a1 = np.array([1, 2, 3])    #Creating a numpy array from a regular Python array
a2 = np.arange(10)          #Similar to Python's "range()", it creates a list filled with values from 0 to 9 in this case
a3 = np.zeros((2, 3))       #Creates a 2x3 list pre-filled with zeroes
a4 = np.ones((2, 3))        #Creates a 2x3 list pre-filled with ones

In [24]:
#Test your arrays here
display(a1)

array([1, 2, 3])

# np.linspace(a, b, n)

Is a function that creates a 1 dimention array, where `n` is the length, and contains points between `a` and `b`, with regular distance. The distance between each point will be `(b - a)/(n - 1)`

In [25]:
#like np.array, but in this case we are creating 11 real values from 0 and 1
a5 = np.linspace(0, 1, 11) 
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Data types

Numpy arrays, in this case for example, will allow only `float64` data types. If you try to append another data type, it will throw an error.

In [26]:
a5.dtype

dtype('float64')

# Array dimentions

The method `shape` will return a tuple with the dimentions of the array.
For example, the variable `a1` shape will return `(3,)` because is a 1 dimention array (a vector using math terms)
And the variable `a3` shape will return `(2, 3)` becaise it's a matrix

Let's see it

In [31]:
display(a1.shape)
display(a3.shape)

(3,)

(2, 3)

# Are two arrays the same?

With the `np.array_equal(a, b)` method we can check if two arrays are the same

In [52]:
b1 = np.array([1, 2, 3])
b2 = np.array([[1, 2, 3]])

np.array_equal(b1, b2)

False

# Reshaping

Numpy arrays have a method called `reshape((2, 3))`. As parameter, it gets a tuple with two values with the new dimentions

In [53]:
b1 = b1.reshape((1, a1.shape[0])) #reshaping b2 by 1x3

#now b1 and b2 are the same
np.array_equal(b1, b2)

True

# Element access and Slicing

We can access to Array elements with `w[a, b]`, where `w` is our matrix, `a` is the line and `b` is the column.
**Remember** that the elements are indexed from 0.

This is an example for two dimentional arrays, if you want to access to a three dimentions array, you can do it with `w[a, b, c]`

Let's create a 3x3 matrix

In [62]:
a = np.array([[1,0,3], [4, 3, 5], [6, 10, -1]])
display(a)

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [63]:
a[0, 2] #accessing to line 0 column 3 element

3

# Creating neutral matrix

In [64]:
a = np.arange(10)
b = np.eye(3)
display(a)
display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
#get first 5 elements of a
a[:5]

array([0, 1, 2, 3, 4])

In [75]:
#get the 3 lines and column 1 of b
b[0:3, 1]

array([0., 1., 0.])

In [76]:
#same example
b[:, 1]

array([0., 1., 0.])

In [77]:
#get last line
b[2, :]

array([0., 0., 1.])

In [78]:
#access to all elements
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Arithmetic operations on Arrays

When we use a arithmetic operator to a np.array, what is happening inside is that the Python interpreter is calling this `ufuncs` or _Universal Functions_:

* `+` calls `np.add`
* `-` calls `np.subtract`
* `*` calls `np.multiply`

In [79]:
a = np.arange(4)

print("a        =", a)      #display the "a" vector
print("a + 5    =", a + 5)  #add 5 to every element
print("a - 5    =", a - 5)  #substract 5 to every element
print("a * 2    =", a * 2)  #multiply by 2 every element
print("a / 2    =", a / 2)  #divide by 2 every element
print("a // 2   =", a // 2) #divide by 2 every element and parse to integer
print("-a       =", -a)     #multiply every element by -1 (get the oposite vector)
print("a ** 2   =", a ** 2) #get square of every element
print("a % 2    =", a % 2)  #mudule of 2 of every vector

a        = [0 1 2 3]
a + 5    = [5 6 7 8]
a - 5    = [-5 -4 -3 -2]
a * 2    = [0 2 4 6]
a / 2    = [0.  0.5 1.  1.5]
a // 2   = [0 0 1 1]
-a       = [ 0 -1 -2 -3]
a ** 2   = [0 1 4 9]
a % 2    = [0 1 0 1]


In [84]:
# Another interesing ufuncs
a = np.arange(4)
b = np.arange(1, 5)

display(np.exp(a))        #get exponential of every element
display(np.log(b))        #get natural logarithm
display(np.sqrt(a))       #square raid
display(np.greater(a, b)) #superior or equal point to point

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

# Perfomance

Numpy runs faster than Python interpreter because it has C++ compiled libraries

Here is a performance test

In [89]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0

for el in a:
    b[i] = el+el
    i += 1

195 ms ± 2.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [90]:
%%timeit
a+a

476 ns ± 1.94 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Statistics and randomness

In [91]:
a = np.arange(10)

display(np.mean(a)) # average
display(np.median(a)) # median

4.5

4.5

In [92]:
np.percentile(a, 40) #get percentile

3.6

In [93]:
np.random.random(10) #generates an array with 10 random elements between 0 and 1

array([0.85528975, 0.12234786, 0.69170134, 0.87291703, 0.27678731,
       0.74136068, 0.05783067, 0.84137208, 0.97259391, 0.3393967 ])