# Why Numpy?

Numpy allow us create better data types for numerical manipulation, which are more efficient than regular Python data types.


In [1]:
#importing numpy
import numpy as np #very common practice
from IPython import display #this library will allow us to display data with type

# Creating arrays

In [23]:
a1 = np.array([1, 2, 3])    #Creating a numpy array from a regular Python array
a2 = np.arange(10)          #Similar to Python's "range()", it creates a list filled with values from 0 to 9 in this case
a3 = np.zeros((2, 3))       #Creates a 2x3 list pre-filled with zeroes
a4 = np.ones((2, 3))        #Creates a 2x3 list pre-filled with ones

In [24]:
#Test your arrays here
display(a1)

array([1, 2, 3])

# np.linspace(a, b, n)

Is a function that creates a 1 dimention array, where `n` is the length, and contains points between `a` and `b`, with regular distance. The distance between each point will be `(b - a)/(n - 1)`

In [25]:
#like np.array, but in this case we are creating 11 real values from 0 and 1
a5 = np.linspace(0, 1, 11) 
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Data types

Numpy arrays, in this case for example, will allow only `float64` data types. If you try to append another data type, it will throw an error.

In [26]:
a5.dtype

dtype('float64')

# Array dimentions

The method `shape` will return a tuple with the dimentions of the array.
For example, the variable `a1` shape will return `(3,)` because is a 1 dimention array (a vector using math terms)
And the variable `a3` shape will return `(2, 3)` becaise it's a matrix

Let's see it

In [31]:
display(a1.shape)
display(a3.shape)

(3,)

(2, 3)

# Are two arrays the same?

With the `np.array_equal(a, b)` method we can check if two arrays are the same

In [52]:
b1 = np.array([1, 2, 3])
b2 = np.array([[1, 2, 3]])

np.array_equal(b1, b2)

False

# Reshaping

Numpy arrays have a method called `reshape((2, 3))`. As parameter, it gets a tuple with two values with the new dimentions

In [53]:
b1 = b1.reshape((1, a1.shape[0])) #reshaping b2 by 1x3

#now b1 and b2 are the same
np.array_equal(b1, b2)

True

# Element access and Slicing

We can access to Array elements with `w[a, b]`, where `w` is our matrix, `a` is the line and `b` is the column.
**Remember** that the elements are indexed from 0.

This is an example for two dimentional arrays, if you want to access to a three dimentions array, you can do it with `w[a, b, c]`

Let's create a 3x3 matrix

In [62]:
a = np.array([[1,0,3], [4, 3, 5], [6, 10, -1]])
display(a)

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [63]:
a[0, 2] #accessing to line 0 column 3 element

3

# Creating neutral matrix

In [64]:
a = np.arange(10)
b = np.eye(3)
display(a)
display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
#get first 5 elements of a
a[:5]

array([0, 1, 2, 3, 4])

In [75]:
#get the 3 lines and column 1 of b
b[0:3, 1]

array([0., 1., 0.])

In [76]:
#same example
b[:, 1]

array([0., 1., 0.])

In [77]:
#get last line
b[2, :]

array([0., 0., 1.])